# ===============================
# GMAIL OTP CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dubeyvikky568@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fxheythbakuqsjyp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CACHE (OTP Expiry)
# ===============================
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=5m,maximumSize=10000