# Gmail SMTP Configuration for OTP
# Get app password from https://myaccount.google.com/apppasswords

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dubeyvikky568@gmail.com
spring.mail.password=fxheythbakuqsjyp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cache config (auto)
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=5m,maximumSize=10000
